export const portfolioData = [
  {
    id: 1,
    name: "CD Entertainment",
    description: "Local DJ & Entertainment Services",
    fullDescription: "A comprehensive entertainment booking platform featuring service packages, event gallery, and client testimonials. Built with modern web technologies for optimal performance and user experience.",
    link: "https://cdentertainment.co",
    image: "/images/portfolio/cdent.webp",
    category: "Web Development",
    technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS", ".NET Core", "PostgreSQL"],
    features: ["Responsive Design", "Contact Forms", "Service Booking", "Photo Gallery"],
    year: "2024",
    status: "Live",
    featured: true,
  },
  {
    id: 2,
    name: "Rosebud Quilting",
    description: "Artisan Quilting & Custom Textile Services",
    fullDescription: "An elegant showcase website for a local quilting artisan, featuring portfolio galleries, custom order forms, and service information. Designed to highlight the craftsmanship and artistic quality of handmade quilts.",
    link: "https://rosebudquilting.com",
    image: "/images/portfolio/rosebud.webp",
    category: "Web Development",
    technologies: ["Next.js", "Custom CSS", "Tailwind CSS", "React"],
    features: ["Portfolio Gallery", "Contact Forms", "Service Pages", "Mobile Responsive"],
    year: "2024",
    status: "Live",
    featured: true,
  },
  {
    id: 3,
    name: "44th Street Tattoo",
    description: "Professional Tattoo Studio & Art Gallery",
    fullDescription: "A striking website for a local tattoo studio featuring artist portfolios, booking system, and aftercare information. Built with a bold, artistic design that reflects the studio's creative atmosphere.",
    link: "https://tattoos44thstreet.com",
    image: "/images/portfolio/44th.webp",
    category: "Web Design",
    technologies: ["Wix", "Custom CSS", "JavaScript"],
    features: ["Artist Portfolios", "Appointment Booking", "Gallery Showcase", "SEO Optimized"],
    year: "2023",
    status: "Live",
    featured: false,
  },
  {
    id: 4,
    name: "O.R.E. Plumbing",
    description: "Local Plumbing Services",
    fullDescription: "A comprehensive website for a local plumbing company, featuring service descriptions, booking forms, and customer testimonials. Built with a focus on user experience and mobile responsiveness.",
    link: "https://www.oreplumbing.com",
    image: "/images/portfolio/ore.webp",
    category: "Web Development",
    technologies: ["Next.js", "ShadCN", "Vercel"],
    features: ["Responsive Design", "Service Booking", "Contact Forms", "Customer Testimonials"],
    year: "2024",
    status: "Live",
    featured: true,
  },
  {
    id: 5,
    name: "Kristina Eck Real Estate",
    description: "Real Estate Agent Portfolio & Listings",
    fullDescription: "A professional portfolio website for a real estate agent, featuring property listings, agent biography, and contact information. Designed to provide a seamless experience for potential clients searching for properties.",
    link: "https://kristinaeck.oakleydye.com",
    image: "/images/portfolio/kristinaeck.webp",
    category: "Web Development",
    technologies: ["Next.js", "Tailwind CSS", "React"],
    features: ["Property Listings", "Agent Bio", "Contact Forms", "Mobile Responsive", "Custom API Integration"],
    year: "2026",
    status: "In Development",
    featured: true,
  },
  {
    id: 6,
    name: "Black Peak Equipment",
    description: "Equipment Rental Platform with eCommerce & Scheduling",
    fullDescription: "A full-featured rental platform for a heavy equipment company, combining an eCommerce storefront with an integrated scheduling system. Customers can browse equipment, check availability, reserve online, and manage their bookings — all in one seamless experience.",
    link: "#",
    image: "",
    category: "Web Development",
    technologies: ["Wordpress", "WooCommerce", "Stripe", "Acuity"],
    features: ["eCommerce Checkout", "Real-time Availability Calendar", "Online Reservations", "Admin Dashboard", "Mobile Responsive"],
    year: "2022",
    status: "Decommissioned",
    featured: false,
  },
  {
    id: 7,
    name: "Rippin' Rentals",
    description: "Adventure Gear & Outdoor Equipment Rental Website",
    fullDescription: "A vibrant website for an outdoor recreation rental company offering kayaks, bikes, camping gear, and more. Features a clean browsing experience, seasonal availability, and a streamlined contact-to-book flow.",
    link: "#",
    image: "",
    category: "Web Development",
    technologies: ["Next.js", "React", "Tailwind CSS", "TypeScript"],
    features: ["Equipment Catalog", "Seasonal Availability", "Contact & Quote Forms", "Mobile Responsive", "SEO Optimized"],
    year: "2023",
    status: "Cancelled",
    featured: false,
  },
  {
    id: 8,
    name: "Wash Away Mobile Detailing",
    description: "Mobile Detailing Booking with Calendar Integration",
    fullDescription: "An online scheduling solution for a mobile detailing business, integrated directly with Google Calendar. Customers select a service, pick an available time slot, and receive instant confirmation — eliminating back-and-forth booking friction.",
    link: "#",
    image: "",
    category: "Custom Applications",
    technologies: ["Acuity Scheduling", ".NET Core", "Google Calendar API"],
    features: ["Real-time Calendar Sync", "Service Selection & Pricing", "Automated Confirmations", "Admin Schedule View", "SMS Reminders"],
    year: "2025",
    status: "Live",
    featured: false,
  },
  {
    id: 9,
    name: "PantryAI",
    description: "AI-Powered Pantry Manager & Recipe Generator",
    fullDescription: "A cross-platform mobile and web app that tracks pantry and fridge inventory, then uses AI to suggest recipes based on what you already have. A built-in price comparison engine cross-references local store prices and recommends the best store to shop based on your shopping list.",
    link: "#",
    image: "",
    category: "Custom Applications",
    technologies: ["React Native", "Next.js", "TypeScript", "OpenAI API", ".NET Core", "PostgreSQL"],
    features: ["AI Recipe Generation", "Pantry Inventory Tracking", "Multi-Store Price Comparison", "Smart Shopping Lists", "Cross-Platform (iOS/Android/Web)"],
    year: "2025",
    status: "In Development",
    featured: false,
  },
  {
    id: 10,
    name: "Billing Workflow Redesign",
    description: "Enterprise Business Process UX Overhaul",
    fullDescription: "Redesigned a complex multi-screen business process workflow that previously spanned 8 separate screens into a single guided stepper interface. The new flow drastically reduced user errors, training time, and task completion time while improving data consistency across the system.",
    link: "#",
    image: "",
    category: "Custom Applications",
    technologies: ["React", "TypeScript", "Single SPA", ".NET Core", "SQL Server", "PostgreSQL", "Azure Service Bus"],
    features: ["Single-Page Stepper Workflow", "Input Validation & Guardrails", "Progress Persistence", "Reduced Completion Time", "Accessibility Compliant"],
    year: "2024",
    status: "Live",
    featured: false,
  },
  {
    id: 11,
    name: "AI Document Processing Pipeline",
    description: "Intelligent Document Data Extraction & Automation",
    fullDescription: "An AI-powered pipeline that ingests scanned documents and unstructured files, extracts key data fields using large language models, and routes structured output into downstream business systems — replacing a previously manual, error-prone data entry process.",
    link: "#",
    image: "",
    category: "System Architecture",
    technologies: ["Python", ".NET Core", "Kodexa AI", "Next.js", "ShadCN UI", "Tailwind CSS", "Azure Blob Storage", "PostgreSQL", "Azure Service Bus", "SQL Server"],
    features: ["Automated Data Extraction", "Multi-format Document Support", "Confidence Scoring", "Human-in-the-Loop Review", "Audit Logging"],
    year: "2025",
    status: "Live",
    featured: false,
  },
  {
    id: 12,
    name: "Cloud Task Scheduler",
    description: "Resilient Distributed Scheduled Task Management",
    fullDescription: "A cloud-native scheduled task management platform built to replace fragile console apps running on physical servers. Supports distributed execution, retry logic, failure alerts, and a management dashboard — with zero downtime deployments and full observability.",
    link: "#",
    image: "",
    category: "System Architecture",
    technologies: [".NET Core", "Azure Functions", "Azure Service Bus", "PostgreSQL", "Hazelcast"],
    features: ["Distributed Execution", "Automatic Retry & Failure Alerts", "Management Dashboard", "Zero-Downtime Deployments", "Full Observability"],
    year: "2025",
    status: "Live",
    featured: false,
  },
  {
    id: 13,
    name: "Integrated Task & Chat Notifications",
    description: "Task Management System with Real-Time Chat Alerts",
    fullDescription: "A task management solution deeply integrated with an internal chat platform to deliver instant, contextual notifications the moment a task is assigned, updated, or escalated. Eliminated missed assignments and reduced average response time significantly.",
    link: "#",
    image: "",
    category: "Custom Applications",
    technologies: [".NET Core", "Google Chat API", "React", "TypeScript", "SQL Server"],
    features: ["Real-Time Push Notifications", "Chat Platform Integration", "Task Lifecycle Tracking", "Escalation Rules", "Audit Trail"],
    year: "2024",
    status: "Live",
    featured: false,
  },
  {
    id: 14,
    name: "Process Metrics Dashboard",
    description: "Custom KPI Visualization & Analytics Dashboard",
    fullDescription: "A bespoke metrics and analytics dashboard giving operations teams real-time visibility into business process performance. Replaces static spreadsheet reports with live, filterable charts and drill-down views — enabling faster decisions based on accurate data.",
    link: "#",
    image: "",
    category: "Custom Applications",
    technologies: ["React", "TypeScript", "Next.js", "Tailwind CSS", "ShadCN UI", ".NET Core", "PostgreSQL"],
    features: ["Real-Time KPI Tracking", "Interactive Charts & Drill-downs", "Custom Date Filters", "Role-Based Access", "Exportable Reports"],
    year: "2025",
    status: "Live",
    featured: false,
  },
];

export const portfolioCategories = [
  "All",
  "Web Development",
  "Web Design",
  "Custom Applications",
  "System Architecture",
  "SEO & Marketing"
];
